server:
    name: GOST Server
    host:
    port: 8080
    externalUri: http://localhost:8080
    maxEntityResponse: 100
    indentedJson: true
    https: false
    httpsCert:
    httpsKey:
database:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: gost
    schema: v1
    ssl: false
    maxIdleConns: 30
    maxOpenConns: 50
mqtt:
    enabled: true
    host: mosquitto
    port: 1883
    prefix: GOST
    clientId: gost
    subscriptionQos: 1
    persistent: true
logger:
    fileName:
    verbose: false
